data class InspectionItem(val name: String, val status: InspectionStatus)

enum class InspectionStatus {
   Yes, NO
}
val trucprecheckItems = listOf(
    InspectionItem("Tyres for pressure (visual check) and tread integrity", InspectionStatus.NO),
    InspectionItem("Wheel Security-Check:All Wheel nut indicators are in place and correctly pointing to each other", InspectionStatus.NO),
    InspectionItem("Brakes", InspectionStatus.NO),
    InspectionItem("Park brake alarm (check test) Functions when ignition is OFF & ON", InspectionStatus.NO),
    InspectionItem("Drain air tanks (full air and air-over-hydraulic systems only)", InspectionStatus.NO),
    InspectionItem("Visual inspection from rear of vehicle at brake pads to ensure they are appear correctly fitted", InspectionStatus.NO),
    InspectionItem("Under Bonnet", InspectionStatus.NO),
    InspectionItem("Engine oil level - also check below vehicle to ensure no oil is leaking.", InspectionStatus.NO),
    InspectionItem("Radiator Coolant level (Engine COLD ONLY)", InspectionStatus.NO),
    InspectionItem("Hose and belts condition", InspectionStatus.NO),
    InspectionItem("Lights and reflectors", InspectionStatus.NO),
    InspectionItem("All lights including clearance lights operational", InspectionStatus.NO),
    InspectionItem("All mirrors, reflectors and lenses intact", InspectionStatus.NO),
    InspectionItem("Turntable mounted hook-up light (that is angled so as to see the jaws around the king pin)", InspectionStatus.NO),
    InspectionItem("Structure and bodywork", InspectionStatus.NO),
    InspectionItem("All panels, floors, and visible structures are suitable for work", InspectionStatus.NO),
    InspectionItem("Leaks of any fluid (oil, fuel, water, refrigerant/coolant, hydraulic / brake fluid)", InspectionStatus.NO),
    InspectionItem("Trailer Landing Legs, underrun protection and other structural bodywork is undamaged and functional", InspectionStatus.NO),
    InspectionItem("Pinch Point Protection in place for each panel and not catching on any part of the trailer when operating door.", InspectionStatus.NO),
    InspectionItem("External Check", InspectionStatus.NO),
    InspectionItem("Windows and mirrors for security, damage and grime", InspectionStatus.NO),
    InspectionItem("Wipers and windscreen washers for ensuring clear forward vision", InspectionStatus.NO),
    InspectionItem("Where applicable, NHVAS/WAHVA/Load Rated Curtain labels correctly affixed, and interception book in cabin.", InspectionStatus.NO),
    InspectionItem("Air lines, electrical leads & EBS are connected and secured to spring / pogo stick and all appear functional Truck/Trailer mudguards are fitted, and free from any holes/open cracks", InspectionStatus.NO),
    InspectionItem("Tow couplings and drawbars checked for security and integrity with no observable issues where applicable", InspectionStatus.NO),
    InspectionItem("Turntable checked, free of any damage/debris and handle not bent, in locked position. Carabiner Clip fitted to handle where applicable Fridge motor checked, within temperature range, and no alarms.", InspectionStatus.NO),
    InspectionItem("Fire extinguisher mounted, in date and serviceable (within 6 months)", InspectionStatus.NO),
    InspectionItem("Registration plate is secured and clean", InspectionStatus.NO),
    InspectionItem("In Cabin Checks", InspectionStatus.NO),
    InspectionItem("Fuel Level Above a Third", InspectionStatus.NO),
    InspectionItem("Fuel Additive / Ad Blue Level Above a Third", InspectionStatus.NO),
    InspectionItem("First Aid Kit available and stocked Necessary permits for operation", InspectionStatus.NO),
    InspectionItem("Safety Triangles × 3", InspectionStatus.NO),
    InspectionItem("Overall Observations", InspectionStatus.NO),
    InspectionItem("Faults or damages to structure/cosmetics", InspectionStatus.NO)
)
val trailerinspectionChecklist = listOf(
    InspectionItem("Accreditation Labels - current and legible", InspectionStatus.NO),
    InspectionItem("Air Lines/Connections/EBS/ABS/ESC/TEBS operational", InspectionStatus.NO),
    InspectionItem("All Other Lights, incl. clearance lights - fitted and operating", InspectionStatus.NO),
    InspectionItem("Brake Lights/Taillights - including rego plate", InspectionStatus.NO),
    InspectionItem("Brakes - are serviceable", InspectionStatus.NO),
    InspectionItem("Fifth Wheel/Turntable", InspectionStatus.NO),
    InspectionItem("Fluid or Air Leaks (including underbody checks)", InspectionStatus.NO),
    InspectionItem("For Fridge Vans - fridge motor, incl. fuel levels", InspectionStatus.NO),
    InspectionItem("Indicators/Hazard Lights", InspectionStatus.NO),
    InspectionItem("Load Scales Operational", InspectionStatus.NO),
    InspectionItem("Load Security/Restraint In Place", InspectionStatus.NO),
    InspectionItem("Reflectors/Lenses - fitted and operational", InspectionStatus.NO),
    InspectionItem("Structure/Bodywork - Secure, Cracks, Damage, Rust", InspectionStatus.NO),
    InspectionItem("Suspension (visual check only) - cracks, leaks, damage", InspectionStatus.NO),
    InspectionItem("Tailgate Lifter", InspectionStatus.NO),
    InspectionItem("Tow Couplings/Drawbar: Secure and no movement", InspectionStatus.NO),
    InspectionItem("Tyres - Tread, Wear, Pressure", InspectionStatus.NO),
    InspectionItem("Wheels/Hubs/Wheel Nut Indicators/Wheel Security", InspectionStatus.NO),
    InspectionItem("Load Plan / Declaration Sheet Checked", InspectionStatus.NO)
)
